### ISSUE TITLE
Error recording: [Errno -9988] Stream closed

### ISSUE THREAD

**Issue by servas089** [SuperShinyEyes/spl-meter-with-RPi#1]
Hi, am trying to implement your project. I am almost done. One (initial) single value is displayed in the browser and written to the 2 log files. Unfortunately it directly exits the program with the following error message:

 (96097) Error recording: [Errno -9988] Stream closed
 (96098) Error recording: [Errno -9988] Stream closed
 (96099) Error recording: [Errno -9988] Stream closed
Traceback (most recent call last):
	File "spl_meter.py", line 117, in <module>
listen()
	File "spl_meter.py", line 92, in listen
print(" (%d) Error recording: %s" % (error_count, e))

Maybe this is something because of the CHUNK value. I have tried serveral values withou success, but I am also not sure how to calculate the correct and value and if it is the cause of the error. 

Looking for any kind of ideas that make me the next step.

thanks
kr

**Comment by SuperShinyEyes** [comment]
Hi, Please specify your setup.

- OS
- HW
- Python version
- Libraries
- whatever you might find useful for debugging.

I don't have a sound card for RPi anymore so I cannot help you if you are using an Rpi.

Br,

**Comment by servas089** [comment]
Hope this information helps a little bit...

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
Raspberr 3
Linux raspberrypi 4.14.30-v7+ #1102
Python 2.7.13, incl. EasyProcess, Pyvirtualdisplay, PyAudio
Numpy 1.12.1
Scipy 0.18.1
Selenium 3.11.0
Wheel 0.29.0-2
pi@raspberrypi:~ $ cat /proc/asound/cards
 0 [Device         ]: USB-Audio - USB Audio Device
                      C-Media Electronics Inc. USB Audio Device at usb-3f980000.usb-1.5, full speed
 1 [ALSA           ]: bcm2835_alsa - bcm2835 ALSA
                      bcm2835 ALSA

Let me know if I can provide any futher useful information
Many thanks in advance

**Comment by SuperShinyEyes** [comment]
Thanks. I will look into this issue next week as I'm on an exam week atm. Let me know if you solve this before me. 

BTW, did this problem occur with my original code or when you tweaked something?
Just to make sure we don't make any silly mistake, can you post `spl_meter.py` which is running on your rpi?

**Comment by servas089** [comment]
Sure, looking for your feedback when you have the time. 
On the other hand, if you do have an old image of your project, I could also try this one to walk around the issue....
kr

**Comment by YBIacous** [comment]
Hello,
I ran in the same problem.
First reading fine (read the dB(A) correctly) then Error stackhoverflow and 

(1205) Error recording: [Errno -9988] Stream closed
(1206) Error recording: [Errno -9988] Stream closed
Traceback (most recent call last):
File "spl_meter.py", line 116, in
listen()
File "spl_meter.py", line 91, in listen
print(" (%d) Error recording: %s" % (error_count, e))

The code is not tweaked, on Pi 2 B. I try a lot of Chunk and Rate number with no sucess.

There is a USB microphone plug to the Pi (the first reading varie according to the noise, so I assume the microphone is not faulty ?).

I really a **# noob** at Pi and programming but good in Acoustics.

I installed all the prerequisite (pyaudio, selenium, etc) but I don't know if I must take the new one or the prerequisite with theyre version number.

I am very sorry to bother you, I think it's my poor knowledge of the programming and Pi stuff that lead me to this point.

All help will be very appreciated

Yannick


For more information there is the Python consol output:

====== RESTART: /home/pi/Bureau/spl-meter-with-RPi-master/spl_meter.py ======
Listening
A-weighted: +24.10 dB
update_max_if_new_is_larger_than_max called
max observed
 (1) Error recording: [Errno -9981] Input overflowed
 (2) Error recording: [Errno -9988] Stream closed
 (3) Error recording: [Errno -9988] Stream closed
 (4) Error recording: [Errno -9988] Stream closed
  
Traceback (most recent call last):
  File "/home/pi/Bureau/spl-meter-with-RPi-master/spl_meter.py", line 116, in <module>
    listen()
  File "/home/pi/Bureau/spl-meter-with-RPi-master/spl_meter.py", line 91, in listen
    print(" (%d) Error recording: %s" % (error_count, e))
  File "/usr/lib/python2.7/idlelib/PyShell.py", line 1356, in write
    return self.shell.write(s, self.tags)
KeyboardInterrupt


And for more information
Pi 2B
pi@raspberrypi:~ $ cat /proc/asound/cards
 0 [ALSA           ]: bcm2835 - bcm2835 ALSA
                      bcm2835 ALSA
 1 [Device         ]: USB-Audio - USB PnP Sound Device
                      C-Media Electronics Inc. USB PnP Sound Device at usb-3f980000.usb-1.5, full spe

**Comment by servas089** [comment]
Hi, I resolved the issue for my instance. The following instructions to activate bluetooth and hci0 solved my problem. 

https://raspberrypi.stackexchange.com/questions/47045/hcitool-scan-says-no-such-device

From my perspective, the issue can be closed. 
thx

**Comment by SuperShinyEyes** [comment]
Hi,

Thank you for letting me know because I just reinstalled the Raspbian OS on my rpi now. :D

Cheers!
