### ISSUE TITLE
Please Add Steps on how to install to Raspberry Pi

### ISSUE THREAD

**Issue by iya17** [SuperShinyEyes/spl-meter-with-RPi#4]
Hi!
I am new to raspberry pi but I have been a long time arduino user.
The video demo in youtube sent me here and I want to try your code.
I am using a Raspberry Pi 3 with a USB mic.
Can you please help us newbies on how to install your library?
I did "git clone https://github.com/SuperShinyEyes/spl-meter-with-RPi"
but I don't know how to install the requirements and I don't know what docker is for.

I hope you can help. Thank you in advance!

**Comment by SuperShinyEyes** [comment]
Hi,

You can try Docker by following the blog post: http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/

I'm sorry but I don't have time to write more detailed instruction.

Br,
